server:
  port: 8111
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springsecurity-test?characterEncoding=utf-8&serverTimezone=UTC
  redis:
    host: 47.93.49.3
    database: 0
    port: 6379
logging:
  level:
    com:
      baomidou:
        mybatisplus:
          mapper: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl